BASE_DIR="/opt/svobodanet"
CONFIG_DIR="/opt/svobodanet/config"
LISTS_DIR="/opt/svobodanet/lists"
OUTPUT_DIR="/opt/svobodanet/output"
CLIENTS_DIR="/opt/svobodanet/output/clients"
MIKROTIK_DIR="/opt/svobodanet/output/mikrotik"
BACKUPS_DIR="/opt/svobodanet/backups"
REPO_DIR="/opt/svobodanet/repo"
SVNET_GIT_URL="https://github.com/kadixLife/SVNET.git"

OVPN_SERVICE="openvpn-server@svnet"
OVPN_NAME="svnet"
OVPN_IF="tun-svnet"
OVPN_PROTO="udp"
OVPN_PORT="1194"
VPN_NET="10.88.0.0/24"
VPN_SERVER_IP="10.88.0.1"
MIKROTIK_VPN_IP="10.88.0.2"

HTTP_SERVICE="svnet-http.service"
HTTP_PORT="8088"

CLIENT_NAME="mikrotik"
MIKROTIK_LAN="192.168.50.0/24"
MIKROTIK_LAN_DNS="192.168.50.1"
MIKROTIK_WAN="pppoe-wan"
MIKROTIK_OVPN_IF="ovpn-svnet"
