# MikroTik_VPN install/update template
# Runtime files are generated by mikrotik-vpn --prepare-mikrotik.

:local mvpnBase "http://{{SERVER_IP}}:{{HTTP_PORT}}"
:local mvpnOvpnFile "mikrotik.ovpn"

:if ([:len [/interface ovpn-client find name="{{MIKROTIK_OVPN_IF}}"]] = 0) do={
    :log warning "MikroTik_VPN: OpenVPN client not found, fetching mikrotik.ovpn"
    :do { /tool fetch url=($mvpnBase . "/clients/mikrotik.ovpn") dst-path=$mvpnOvpnFile keep-result=yes } on-error={ :log warning "MikroTik_VPN: cannot fetch mikrotik.ovpn" }
    :do { /interface ovpn-client import-ovpn-configuration ovpn-configuration=$mvpnOvpnFile ovpn-user=ovpnuser skip-cert-import=no } on-error={ :log warning "MikroTik_VPN: automatic OpenVPN import failed" }
}

:if ([:len [/interface ovpn-client find name="{{MIKROTIK_OVPN_IF}}"]] = 0) do={
    :error "MikroTik_VPN: OpenVPN interface {{MIKROTIK_OVPN_IF}} is missing"
}

:log warning "MikroTik_VPN: use generated mikrotik-vpn-install.rsc from HTTP publish for full rules"
